package br.model.dao;
// Generated 02/11/2016 23:09:33 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EspecialidadeMedica generated by hbm2java
 */
@Entity
@Table(name = "especialidade_medica", catalog = "pahdb")
public class EspecialidadeMedica implements java.io.Serializable {

	private Integer nrSequencia;
	private String dsEspecialidade;

	public EspecialidadeMedica() {
	}

	public EspecialidadeMedica(String dsEspecialidade) {
		this.dsEspecialidade = dsEspecialidade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NR_SEQUENCIA", unique = true, nullable = false)
	public Integer getNrSequencia() {
		return this.nrSequencia;
	}

	public void setNrSequencia(Integer nrSequencia) {
		this.nrSequencia = nrSequencia;
	}

	@Column(name = "DS_ESPECIALIDADE", nullable = false)
	public String getDsEspecialidade() {
		return this.dsEspecialidade;
	}

	public void setDsEspecialidade(String dsEspecialidade) {
		this.dsEspecialidade = dsEspecialidade;
	}

}
