package br.model.dao;
// Generated 02/11/2016 23:09:33 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teste generated by hbm2java
 */
@Entity
@Table(name = "teste", catalog = "pahdb")
public class Teste implements java.io.Serializable {

	private int idteste;
	private String testecol;

	public Teste() {
	}

	public Teste(int idteste) {
		this.idteste = idteste;
	}

	public Teste(int idteste, String testecol) {
		this.idteste = idteste;
		this.testecol = testecol;
	}

	@Id

	@Column(name = "idteste", unique = true, nullable = false)
	public int getIdteste() {
		return this.idteste;
	}

	public void setIdteste(int idteste) {
		this.idteste = idteste;
	}

	@Column(name = "testecol", length = 45)
	public String getTestecol() {
		return this.testecol;
	}

	public void setTestecol(String testecol) {
		this.testecol = testecol;
	}

}
